spring:
  application:
    name: mcp-client
  main:
    web-application-type: none

  shell:
    interactive:
      enabled: true

  ai:
    ollama:
      chat:
        model: llama3.2
        base-url: http://ollama:11434
      embedding:
        model: nomic-embed-text
        base-url: http://ollama:11434
    mcp:
      client:
        stdio:
          servers-configuration: classpath:./mcp-servers-config.json
        # connections:
        #   filesystem:
        #     command: npx
        #     args: -y,@modelcontextprotocol/server-filesystem,/tmp/resource-data
        #   read-file-mcp:
        #     command: java
        #     args: -jar,/home/everton/projects/java/read-file-mcp/build/libs/read-file-mcp-1.0.0.jar,--folder.path=/tmp/resource-data
      